name: Pull Request Handler

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Checks for Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Look to See if Conventional Commits were Used
        id: check_commits
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix,debug"

      - name: Auto Close PR if the Check Commits Fails (i.e. the submitter was a very bad student)
        id: auto_close
        continue-on-error: true
        if: steps.check_commits.outcome == 'failure'
        uses: peter-evans/close-pull@v3
        with:
          comment: "The PR has Auto Closed b/c you did not follow the Conventional Commit Rules."

      - name: Send Email Using SendGrid API
        id: send_email
        if: steps.check_commits.outcome == 'failure'
        run: |
          curl --request POST --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $API_KEY" --header 'Content-Type: application/json' \
          --data '{"personalizations": [{"to": [{"email": "cchemero@dons.usfca.edu"}]}],"from": {"email": "cchemero@dons.usfca.edu"},"subject": "Notification to Developer...Non Conventional Commits - PR Closed","content": [{"type": "text/plain", "value": "Reopen properly!!"}]}'
        env:
          API_KEY: ${{ secrets.SENDGRID_API_KEY}}