name: Conventional Commit Checker - V2

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Checks for Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Look to See if Conventional Commits were Used
        id: check_commits
        continue-on-error: true
        uses: webiny/action-conventional-commits@v1.3.0
        with:
          allowed-commit-types: "feat,fix"

      - name: Auto Close PR if the Check Commits Fails (i.e. the submitter was a very bad student)
        id: auto_close
        continue-on-error: true
        if: steps.check_commits.outcome == 'failure'
        uses: peter-evans/close-pull@v3
        with:
          comment: "Your PR has Auto Closed b/c you did not follow the Conventional Commit Rules...Bad!"

      - name: Send Email Using SendGrid API
        id: send_email
        if: steps.check_commits.outcome == 'failure'
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.sendgrid.net
          server_port: 587
          username: apikey
          password: ${{ secrets.SENDGRID_API_KEY }}
          subject: "PR #${{ github.event.pull_request.number }} Auto Closed - You didn't follow the rules..."
          body: |
            PR: #${{ github.event.pull_request.number }} has been closed automatically b/c Conventional Commits weren't used.
            REPO: ${{ github.repository }}
            PR REF: ${{ github.event.pull_request.html_url }}
          to: "cac692@nyu.edu"
          from: "bugles_tycoons_6y@icloud.com"
