name: Nightly Automated Build
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build-artifact-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Log Time for Reference
        id: log_date
        run: date

      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v4

      - name: Python Setup
        id: python_setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python Requirements
        id: install_deps
        run: |
          python -m venv chemch-t
          source chemch-t/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run Python Tests
        id: run_tests
        run: |
          source chemch-t/bin/activate
          export $(grep -v '^#' .env | xargs)
          pytest src/tests/

      - name: Send Email Notification Using SendGrid API for Failure
        id: send_email
        if: failure()
        run: |
          curl --request POST --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $API_KEY" --header 'Content-Type: application/json' \
          --data '{"personalizations": [{"to": [{"email": "cchemero@dons.usfca.edu"}]}],"from": {"email": "cac692@gmail.com"},"subject": "Python Build Failed!","content": [{"type": "text/plain", "value": "Log in now to investigate!"}]}'
        env:
          API_KEY: ${{ secrets.SENDGRID_API_KEY}}
