name: Daily Build
on:
  schedule:
    - cron: '*/1 * * * *'
#  workflow_dispatch:

jobs:
  build-artifact-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Log Time for Reference
        id: log_date
        run: date

      - name: Checkout Code
        id: checkout_code
        uses: actions/checkout@v3

      - name: Python Setup
        id: python_setup
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Python Requirements
        id: install_dependencies
        run: |
          pip install -r requirements.txt
          pip install python-dotenv pytest

      - name: Send Email Notification Using SendGrid API for Failure
        id: send_email
        if: failure()
        run: |
          curl --request POST --url https://api.sendgrid.com/v3/mail/send \
          --header "Authorization: Bearer $API_KEY" --header 'Content-Type: application/json' \
          --data '{"personalizations": [{"to": [{"email": "cchemero@dons.usfca.edu"}]}],"from": {"email": "cac692@gmail.com"},"subject": "Python Build Failed!","content": [{"type": "text/plain", "value": "Log in now to investigate!"}]}'
        env:
          API_KEY: ${{ secrets.SENDGRID_API_KEY}}
